name: Update ClickUp on Commit

on:
  push:
    branches: [ main, master, develop ]  # Add your branch names
    # Optionally include feature branches:
    # branches: [ main, master, develop, 'feature/**' ]

jobs:
  update-clickup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Fetch current and previous commit for diff
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openai
    
    - name: Update ClickUp
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CLICKUP_API_KEY: ${{ secrets.CLICKUP_API_KEY }}
        CLICKUP_TEAM_ID: ${{ secrets.CLICKUP_TEAM_ID }}
      run: python .github/scripts/update_clickup.py
